# Uncomment the next line to define a global platform for your project
# platform :osx, '10.15'

target 'DNLocalMusicPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DNLocalMusicPlayer
  pod 'RxCocoa'

end
